services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: psmsql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:?error}
    platform: linux/amd64
    ports:
      - "1433:1433"
    env_file:
      - ./config/psmsql.env